### ISSUE TITLE
SyntaxError: export declarations may only appear at top level of a module

### ISSUE THREAD

**Issue by paulgoldie** [willmcpo/body-scroll-lock#157]
Hi!

I just include the Script with <script src="..."></script> an got the error:

"SyntaxError: export declarations may only appear at top level of a module".

Can you help me?

Greets

**Comment by benhuson** [comment]
I also get similar errors when trying to include with just the <script> tag and using Vanilla JS.

**Comment by diachedelic** [comment]
What is the `src` attribute on your `<script>` tag?

**Comment by jrDev1** [comment]
hello,

I had this issue until I realized I was using the js version from the src folder. I found the correct file in the lib folder and used the raw version from here: https://github.com/willmcpo/body-scroll-lock/blob/master/lib/bodyScrollLock.js

Hope this helps someone since I gave up then came back; this should some else save some time!

Thanks,
jrDev

**Comment by diachedelic** [comment]
thanks @jrDev1
